### ISSUE TITLE
Error writing PDF file

### ISSUE THREAD

**Issue by PatrickDeelen** [molgenis/systemsgenetics#16]
I get the following error when running an eQTL mapping using the new build.

Error explained here: http://itext-general.2136553.n4.nabble.com/com-lowagie-text-exceptions-IllegalPdfSyntaxException-Unbalanced-save-restore-state-operators-td4536784.html

Are we using a newer version of the itext package?????

```
Now reading real data: /target/gpfs2/gcc/home/pdeelen/Projects/RnaSeqEqtl/testEncode/eQtlGene//eQTLs.txt.gz
|########################| 100% - T: 6s T-: 0 ns #: 37006/37006
Number of unique P Values:      683
Number of significant eQTLs:    0
 - Number of unique SNPs, constituting an eQTL: 129465
 - Number of unique probes, constituting an eQTL:       23376
com.lowagie.text.exceptions.IllegalPdfSyntaxException: Unbalanced save/restore state operators.
        at com.lowagie.text.pdf.PdfContentByte.sanityCheck(PdfContentByte.java:3127)
        at com.lowagie.text.pdf.PdfContentByte.reset(PdfContentByte.java:1282)
        at com.lowagie.text.pdf.PdfContentByte.reset(PdfContentByte.java:1271)
        at com.lowagie.text.pdf.PdfWriter.resetContent(PdfWriter.java:740)
        at com.lowagie.text.pdf.PdfDocument.initPage(PdfDocument.java:1147)
        at com.lowagie.text.pdf.PdfDocument.newPage(PdfDocument.java:965)
        at com.lowagie.text.pdf.PdfDocument.close(PdfDocument.java:813)
        at com.lowagie.text.Document.close(Document.java:495)
        at eqtlmappingpipeline.metaqtl3.graphics.EQTLDotPlot.draw(EQTLDotPlot.java:200)
        at eqtlmappingpipeline.metaqtl3.MetaQTL3.mapEQTLs(MetaQTL3.java:824)
        at eqtlmappingpipeline.metaqtl3.MetaQTL3ConsoleGUI.<init>(MetaQTL3ConsoleGUI.java:137)
        at eqtlmappingpipeline.gui.EQTLMappingPipelineConsole.main(EQTLMappingPipelineConsole.java:66)
        at eqtlmappingpipeline.Main.main(Main.java:23)
```

**Comment by ranibsk** [comment]
Hello sir,
       Can you please tell how you Fix this Issue?
