### ISSUE TITLE
CTSASE coupling file bug

### ISSUE THREAD

**Issue by CGUTA** [molgenis/systemsgenetics#441]
If the BAM file column (2nd) in the --coupling file contains dots or underscores because the name of the BAM contains them. a mapping error ocurrs.

BAMS/HG00099.5.M_120131_3.bam
Location of bam file is an existing file, will continue.
Sample names were loaded.
sample_name: HG00099
sample_map:  {HG00097.7.M_120219_2=0}
Exception in thread "main" java.lang.IllegalArgumentException: Couldn't find the filename in the sample names. Quitting.
	at nl.systemsgenetics.cellTypeSpecificAlleleSpecificExpression.ReadGenoAndAsFromIndividual.readGenoAndAsFromIndividual(ReadGenoAndAsFromIndividual.java:180)
	at nl.systemsgenetics.cellTypeSpecificAlleleSpecificExpression.MainEntryPoint.main(MainEntryPoint.java:325)

**Comment by adriaan-vd-graaf** [comment]
Hi sorry for the late reply, 
I've overlooked this issue. Thank you for briningin it up, I will sort it out in a later version of the program
Thanks, Adriaan
