### ISSUE TITLE
GenotypeHarmonizer installation issue?

### ISSUE THREAD

**Issue by anderseng** [molgenis/systemsgenetics#473]
When I try to run GenotypeHarmonizer, I get the following error.  I am not sure what "Unsupported major.minor version" means.  Can you advise on how to troubleshoot?

Thank you very much!
Gen

**GenotypeHarmonizer.sh
Exception in thread "main" java.lang.UnsupportedClassVersionError: nl/umcg/deelenp/genotypeharmonizer/GenotypeHarmonizer : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:634)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
Could not find the main class: nl.umcg.deelenp.genotypeharmonizer.GenotypeHarmonizer. Program will exit.**

**Comment by anderseng** [comment]
It was the version of Java.  switched to java 1.7 and it works.  Thanks.
