### ISSUE TITLE
"Error writing output data:Trying to write alleles" Issue?

### ISSUE THREAD

**Issue by The-Standard-Deviant** [molgenis/systemsgenetics#492]
When running Genotypeharmonizer, I come across an error:
Input:
GenotypeHarmonizer.sh --input file --o file2 -r reference.file -R VCF

Output:
Writing results

**Error writing output data: Trying to write alleles [G] for G\A SNP.**

I've used GenotypeHarmonizer on previous chr without issue so far. Do you have suggestions on how exactly to find out more about this error? I wasn't able to find an answer in the documentation. Thank you very much

**Comment by PatrickDeelen** [comment]
Could you please share your log file. This should contain a bit more information on the error.

**Comment by The-Standard-Deviant** [comment]
FATAL - Error writing output data: Trying to write alleles [G] for G\A SNP
org.molgenis.genotype.GenotypeDataException: Trying to write alleles [G] for G\A SNP 
at org.molgenis.genotype.plink.BedBimFamGenotypeWriter.writeBimBedFile(BedBimFamGenotypeWriter.java:178)
at org.molgenis.genotype.plink.BedBimFamGenotypeWriter.write(BedBimFamGenotypeWriter.java:74)
        at org.molgenis.genotype.plink.BedBimFamGenotypeWriter.write(BedBimFamGenotypeWriter.java:55)
        at nl.umcg.deelenp.genotypeharmonizer.GenotypeHarmonizer.main(GenotypeHarmonizer.java:421)

**Comment by PatrickDeelen** [comment]
Thank you, I will have a look
