### ISSUE TITLE
Decon-eQTL - dosage file missing values

### ISSUE THREAD

**Issue by mooreann** [molgenis/systemsgenetics#589]
Is Decon-eQTL equipped to deal with dosage genotype files that are missing values? If so, what should missing values be? Or will I be required to just drop the SNPs with any missing values?

Currently I have tried replacing missing values with empty string and 'NA' strings and have gotten similar errors:

Exception in thread "main" java.lang.NumberFormatException: For input string: "NA"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at main.java.decon_eQTL.Utils.StringVectorToDoubleArrayList(Utils.java:133)
	at main.java.decon_eQTL.GenotypeData.<init>(GenotypeData.java:38)
	at main.java.decon_eQTL.Deconvolution.readInputData(Deconvolution.java:47)
	at main.java.decon_eQTL.Main.main(Main.java:24)

**Comment by npklein** [comment]
I released a new version (v1.4, [Decon-eQTL-v1.4-jar-with-dependencies.jar](https://github.com/molgenis/systemsgenetics/releases/download/v1.4/Decon-eQTL-v1.4-jar-with-dependencies.jar)) that should be able to handle missing genotypes. 

The missing genotypes should be encoded as -1.
