### ISSUE TITLE
Error during GADO prioritisation when it encounters an unexpected HPO term

### ISSUE THREAD

**Issue by souzadevinicius** [molgenis/systemsgenetics#671]
### Description

An experiment that executes GADO prioritisation with these parameters _(Note: the file paths are just for example purposes)_:

Process Command

```bash
java -jar GadoCommandline-1.0.1/GADO.jar \
--mode PROCESS \
--output hpoProcessed.txt \
--caseHpo input_cases.txt \
--hpoOntology hp.obo \
--hpoPredictionsInfo predictions_auc_bonf.txt
```

Prioritise Command

```bash
java -jar GadoCommandline-1.0.1/GADO.jar \
--mode PRIORITIZE \
--output results \
--caseHpoProcessed hpoProcessed.txt \
--genes hpo_prediction_genes.txt \
--hpoPredictions genenetwork_bonf_spiked.dat
```

### Error Output

```bash
INFO - DEPICT1.0.1
INFO - Current date and time: 2024-05-28 15:56:30
INFO - Supplied options:
INFO -  * Mode: PROCESS
INFO -  * Output: /nfs/production/parkinso/spot/pheval/monarch_pheval/results/gado-1.0.1-4k/tool_input_commands/hpoProcessed.txt
INFO -  * Case HPO terms: /nfs/production/parkinso/spot/pheval/monarch_pheval/results/gado-1.0.1-4k/tool_input_commands/input_cases.txt
INFO -  * HPO ontology file: /nfs/production/parkinso/spot/pheval/monarch_pheval/configurations/gado-1.0.1-4k/../../runners/gado/hp.obo
INFO -  * Prediction info file: /nfs/production/parkinso/spot/pheval/monarch_pheval/configurations/gado-1.0.1-4k/../../runners/gado/predictions_auc_bonf.txt
INFO - Warning term not found for: HP:0034307 of sample: PMID_10662742_II-1
FATAL - Error: No term named 'HP:0034307'
java.util.NoSuchElementException: No term named 'HP:0034307'
	at org.biojava.nbio.ontology.Ontology$Impl.getTerm(Ontology.java:349)
	at nl.systemsgenetics.gadocommandline.ProcessCaseHpo.process(ProcessCaseHpo.java:104)
	at nl.systemsgenetics.gadocommandline.GadoCommandline.main(GadoCommandline.java:111)
```

### Auxiliar Files
These files were used in the process and prioritisation commands:
[input_cases.txt](https://github.com/user-attachments/files/15782969/input_cases.txt)
[hpoProcessed.txt](https://github.com/user-attachments/files/15782982/hpoProcessed.txt)

**Comment by PatrickDeelen** [comment]
I have uploaded the latest version here: https://github.com/molgenis/systemsgenetics/releases/download/GADO_1.0.4/GadoCommandline-1.0.4.tar.gz

Please let met know if the error is also present in this version, then I will have a look at the code

**Comment by souzadevinicius** [comment]
> I have uploaded the latest version here: https://github.com/molgenis/systemsgenetics/releases/download/GADO_1.0.4/GadoCommandline-1.0.4.tar.gz
> 
> Please let met know if the error is also present in this version, then I will have a look at the code

Unfortunately, the error persists...

**Comment by PatrickDeelen** [comment]
Debugging is a bit tricky because the line number in your version don't add up to my code base. Could you please run using this snapshot: https://filesender.surf.nl/?s=download&token=a315dd96-6ab1-414a-bb7d-f8e76551756e and then share the output. Then I can see what is going wrong.
