### ISSUE TITLE
GADO Error with Obsolete Term Handling in `PROCESS` Mode

### ISSUE THREAD

**Issue by yaseminbridges** [molgenis/systemsgenetics#674]
## Description

While running GADO in PROCESS mode, the program encounters an error when handling an obsolete HPO term (HP:0030214). The error message suggests that alternative terms must be found manually, and the process stops.

## Output
```
  /---------------------------------------\
  |                 GADO                  |
  |                                       |
  |  University Medical Center Groningen  |
  \---------------------------------------/

          --- Version: 1.0.4 ---

More information: http://molgenis.org/systemsgenetics

Current date and time: 2024-11-29 23:41:34

Supplied options:
 * Mode: PROCESS
 * Output: hpoProcessed.txt
 * Case HPO terms: input_cases.txt
 * HPO ontology file: hp.obo
 * Prediction info file: predictions_auc_bonf.txt
Problem running mode: PROCESS
Error message: Obsolete term cannot be handeld. Please find alternative manually: HP:0030214
See log file for stack trace
Error: Obsolete term cannot be handeld. Please find alternative manually: HP:0030214
java.lang.RuntimeException: Obsolete term cannot be handeld. Please find alternative manually: HP:0030214
        at nl.systemsgenetics.gadocommandline.HpoFinder.getPredictableTerms(HpoFinder.java:104) ~[GADO.jar:?]
        at nl.systemsgenetics.gadocommandline.ProcessCaseHpo.process(ProcessCaseHpo.java:116) ~[GADO.jar:?]
        at nl.systemsgenetics.gadocommandline.GadoCommandline.main(GadoCommandline.java:147) ~[GADO.jar:?]
```

## Files
[input_cases.txt](https://github.com/user-attachments/files/17977127/input_cases.txt)
[hpoProcessed.txt](https://github.com/user-attachments/files/17977129/hpoProcessed.txt)

**Comment by PatrickDeelen** [comment]
This is expected behavior of GADO.  We can't automatically map obsolete terms that are no longer part of HPO. 

In these cases it is best to either remove this term or find the new term. In this case it might be: https://www.ebi.ac.uk/ols4/ontologies/hp/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHP_5200321?lang=en
